location                   = "eastus"
resource_group_name_prefix = "step-by-step"
keyvault_name_prefix       = "s-by-s"
resource_group_name_suffix = "my-rg"
replication_location       = "westus"
key_vault_name             = "keyvault"
namespace                  = "Dev"
appname                    = "enterprize-app-service-principal-terraform"
